# Generated by Django 5.2.5 on 2026-03-05 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0001_initial'),
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(help_text='What was measured (e.g., pH, temperature, absorbance)', max_length=255)),
                ('value', models.DecimalField(decimal_places=10, help_text='Measured value', max_digits=20)),
                ('unit', models.CharField(help_text='Unit of measurement (e.g., pH, °C, AU, mg/L)', max_length=50)),
                ('measured_at', models.DateTimeField(help_text='When the measurement was taken (instrument timestamp)')),
                ('data_hash', models.CharField(editable=False, help_text='SHA-256 hash of measurement data for integrity verification', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(help_text='Instrument that produced this reading', on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='instruments.instrument')),
                ('sample', models.ForeignKey(help_text='Sample this measurement belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='samples.sample')),
            ],
            options={
                'indexes': [models.Index(fields=['sample', 'created_at'], name='measurement_sample__32f214_idx'), models.Index(fields=['instrument', 'measured_at'], name='measurement_instrum_777d95_idx')],
            },
        ),
    ]
