# Generated by Django 5.2.5 on 2026-03-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='idempotency_key',
            field=models.UUIDField(blank=True, db_index=True, help_text='UUID from the hub WAL to prevent duplicate ingestion on retry', null=True, unique=True),
        ),
    ]
