# Generated by Django 5.2.5 on 2026-04-22 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_add_context_and_config'),
        ('measurements', '0002_measurement_idempotency_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(blank=True, help_text='Pseudonymized operator identifier (never PII)', max_length=255)),
                ('lot_number', models.CharField(blank=True, help_text='Lot/batch number being tested', max_length=255)),
                ('method', models.CharField(blank=True, help_text='Analytical method reference (e.g., USP <621>, Ph. Eur. 2.2.25)', max_length=255)),
                ('sample_id', models.CharField(blank=True, help_text='External sample identifier from the QC workflow', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Free-text operator notes or observations')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this context record was created')),
                ('instrument', models.ForeignKey(help_text='Instrument that produced this reading (denormalized for query performance)', on_delete=django.db.models.deletion.PROTECT, related_name='measurement_contexts', to='instruments.instrument')),
                ('measurement', models.OneToOneField(help_text='The measurement this context belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='context', to='measurements.measurement')),
            ],
            options={
                'indexes': [models.Index(fields=['instrument', 'timestamp'], name='measurement_instrum_09cb48_idx'), models.Index(fields=['lot_number'], name='measurement_lot_num_7cb100_idx'), models.Index(fields=['operator'], name='measurement_operato_cfe4da_idx')],
            },
        ),
    ]
