# Generated by Django 5.2.5 on 2026-05-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationPushLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_object_type', models.CharField(choices=[('quality_event__v', 'quality_event__v'), ('document__v', 'document__v'), ('audit_attachment__v', 'audit_attachment__v')], help_text='Veeva Vault object type the payload was destined for.', max_length=64)),
                ('source_measurement_id', models.IntegerField(blank=True, db_index=True, help_text='ID of the BioNexus Measurement that triggered this push, when applicable. Null for non-measurement pushes (e.g. standalone document attachments).', null=True)),
                ('source_report_id', models.IntegerField(blank=True, db_index=True, help_text='ID of the BioNexus CertifiedReport, for document pushes.', null=True)),
                ('payload_hash', models.CharField(db_index=True, help_text='SHA-256 hex of the canonical payload sent to Vault.', max_length=64)),
                ('target_object_id', models.CharField(blank=True, default='', help_text='Vault-assigned object ID returned on success (e.g. VVQE-001234). Empty string until a successful response is recorded.', max_length=128)),
                ('http_status', models.IntegerField(blank=True, help_text='HTTP status code from Vault on the most recent attempt.', null=True)),
                ('response_body_excerpt', models.TextField(blank=True, default='', help_text='First 2 KB of the Vault response body, for debugging.')),
                ('last_error', models.TextField(blank=True, default='', help_text='Most recent error message (transport, parse, or Vault).')),
                ('attempts', models.IntegerField(default=0, help_text='Number of push attempts made so far.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_flight', 'In flight'), ('success', 'Success'), ('failed', 'Failed (will retry)'), ('dead_letter', 'Dead letter (max retries exceeded)')], db_index=True, default='pending', max_length=16)),
                ('mode', models.CharField(choices=[('disabled', 'Disabled'), ('mock', 'Mock'), ('sandbox', 'Sandbox'), ('prod', 'Production')], default='disabled', help_text='VEEVA_MODE active at the moment of the push attempt.', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('succeeded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'integrations_veeva_push_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='iv_pushlog_status_created_idx')],
            },
        ),
    ]
