# Generated by Django 5.2.5 on 2026-05-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations_veeva', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationpushlog',
            name='vendor',
            field=models.CharField(choices=[('veeva', 'Veeva Vault QMS'), ('empower', 'Waters Empower'), ('labware', 'LabWare LIMS'), ('starlims', 'STARLIMS'), ('benchling', 'Benchling ELN')], db_index=True, default='veeva', help_text='Which downstream system the push targeted.', max_length=32),
        ),
        migrations.AlterField(
            model_name='integrationpushlog',
            name='target_object_type',
            field=models.CharField(choices=[('quality_event__v', 'quality_event__v'), ('document__v', 'document__v'), ('audit_attachment__v', 'audit_attachment__v'), ('result', 'result'), ('sample', 'sample'), ('entry', 'entry')], help_text='Object type the payload was destined for (vendor-specific).', max_length=64),
        ),
    ]
