# Generated by Django 5.2.5 on 2026-05-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations_veeva', '0002_integrationpushlog_vendor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VeevaOAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token_enc', models.TextField(blank=True, help_text='Fernet-encrypted OAuth2 access token. Refreshed automatically.')),
                ('refresh_token_enc', models.TextField(blank=True, help_text='Fernet-encrypted OAuth2 refresh token. Long-lived.')),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='When the cached access token expires (UTC).', null=True)),
                ('oauth_state', models.CharField(blank=True, help_text='CSRF state token for the current authorize flow. Cleared once the callback succeeds, or after 10 min.', max_length=128)),
                ('oauth_state_created_at', models.DateTimeField(blank=True, help_text='When the active state token was minted (10-min TTL).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Veeva OAuth2 token',
                'verbose_name_plural': 'Veeva OAuth2 tokens',
                'db_table': 'integrations_veeva_oauth_token',
            },
        ),
    ]
