# Generated by Django 5.2.5 on 2026-02-24 09:15

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("protocols", "0002_protocol_deleted_at_protocol_is_deleted_and_more"),
        ("samples", "0003_sample_deleted_at_sample_is_deleted_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "equipment_id",
                    models.CharField(
                        help_text="Unique equipment identifier (from parsed file)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "equipment_name",
                    models.CharField(help_text="Human-readable name", max_length=255),
                ),
                (
                    "equipment_type",
                    models.CharField(
                        choices=[
                            ("liquid_handler", "Liquid Handler (Hamilton, Tecan)"),
                            ("spectrophotometer", "Spectrophotometer"),
                            ("plate_reader", "Plate Reader (Fluor, Absorbance)"),
                            ("incubator", "Incubator"),
                            ("centrifuge", "Centrifuge"),
                            ("pcr_machine", "PCR/qPCR Machine"),
                            ("microscope", "Microscope"),
                            ("freezer", "Freezer Storage"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Physical location in lab", max_length=255
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        help_text="Serial number for traceability",
                        max_length=100,
                    ),
                ),
                (
                    "last_calibration",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last calibration date (critical for accuracy)",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("operational", "Operational"),
                            ("maintenance", "In Maintenance"),
                            ("broken", "Broken"),
                            ("decommissioned", "Decommissioned"),
                        ],
                        default="operational",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["equipment_name"],
            },
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codename",
                    models.CharField(
                        choices=[
                            ("sample:view", "View samples"),
                            ("sample:create", "Create samples"),
                            ("sample:update", "Update samples"),
                            ("sample:delete", "Delete samples"),
                            ("protocol:view", "View protocols"),
                            ("protocol:create", "Create protocols"),
                            ("protocol:update", "Update protocols"),
                            ("protocol:delete", "Delete protocols"),
                            ("audit:view", "View audit logs"),
                            ("audit:export", "Export audit logs"),
                            ("user:manage", "Manage users"),
                            ("role:manage", "Manage roles"),
                        ],
                        help_text="Machine-readable permission identifier",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Human-readable description"
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission",
                "ordering": ["codename"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("admin", "Administrator"),
                            ("principal_investigator", "Principal Investigator"),
                            ("lab_technician", "Lab Technician"),
                            ("auditor", "Auditor (Read-only)"),
                            ("viewer", "Viewer (Read-only)"),
                        ],
                        help_text="Standardized role name",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of role responsibilities"
                    ),
                ),
            ],
            options={
                "verbose_name": "Role",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Laboratory or organization name",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe identifier for the tenant", unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Organizational description"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Inactive tenants are soft-deleted"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tenant (Laboratory)",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Inactive users cannot log in"
                    ),
                ),
                (
                    "last_login_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of last successful login (for audit)",
                        null=True,
                    ),
                ),
                (
                    "last_login_user_agent",
                    models.TextField(
                        blank=True, help_text="User agent of last login (for audit)"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        help_text="The role assigned to this user",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="core.role",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="The tenant (laboratory) this user belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        help_text="Model name (e.g., 'Sample', 'Protocol')",
                        max_length=50,
                    ),
                ),
                (
                    "entity_id",
                    models.BigIntegerField(
                        help_text="Primary key of the affected entity"
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                        ],
                        help_text="CREATE, UPDATE, or DELETE",
                        max_length=10,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When the operation occurred (UTC, immutable, set explicitly)",
                    ),
                ),
                (
                    "user_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="ID of user who triggered the operation (future: auth system)",
                        null=True,
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email of user (for readability, actual proof is signature)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        default=dict,
                        help_text="{'field_name': {'before': old_value, 'after': new_value}, ...}",
                    ),
                ),
                (
                    "snapshot_before",
                    models.JSONField(
                        default=dict,
                        help_text="Full entity state BEFORE mutation (for forensics)",
                    ),
                ),
                (
                    "snapshot_after",
                    models.JSONField(
                        default=dict, help_text="Full entity state AFTER mutation"
                    ),
                ),
                (
                    "signature",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256(previous_signature + json(this_record))",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "previous_signature",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="SHA-256 of the previous audit log (chain proof)",
                        max_length=64,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log Entry",
                "verbose_name_plural": "Audit Log Entries",
                "db_table": "audit_log",
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id", "timestamp"],
                        name="audit_log_entity__cd587a_idx",
                    ),
                    models.Index(
                        fields=["signature"], name="audit_log_signatu_3264db_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="audit_log_timesta_e8e14e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RawFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        help_text="Original filename from upload", max_length=255
                    ),
                ),
                (
                    "file_content",
                    models.BinaryField(
                        help_text="Complete file content (never modified)"
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 hash of file content (proof of originality)",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("file_size", models.BigIntegerField(help_text="File size in bytes")),
                (
                    "mime_type",
                    models.CharField(
                        help_text="MIME type (e.g., 'text/csv', 'application/pdf')",
                        max_length=100,
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When file was uploaded"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft delete flag (content preserved for audit)",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who uploaded the file",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant (lab) that uploaded the file",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_files",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Raw File",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ParsedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "extracted_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When AI extraction occurred"
                    ),
                ),
                (
                    "parsed_json",
                    models.JSONField(
                        help_text="Raw AI-extracted data (not yet validated)"
                    ),
                ),
                (
                    "extraction_confidence",
                    models.FloatField(help_text="AI confidence score (0.0 to 1.0)"),
                ),
                (
                    "extraction_model",
                    models.CharField(
                        help_text="Which AI model was used (e.g., 'gpt-4-turbo')",
                        max_length=100,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Awaiting Validation"),
                            ("validated", "Human Confirmed"),
                            ("rejected", "Human Rejected"),
                            ("superseded", "Replaced by New Parse"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current validation state",
                        max_length=20,
                    ),
                ),
                (
                    "validated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When human validation occurred",
                        null=True,
                    ),
                ),
                (
                    "validation_notes",
                    models.TextField(
                        blank=True,
                        help_text="Human notes on validation (e.g., corrections made)",
                    ),
                ),
                (
                    "confirmed_json",
                    models.JSONField(
                        blank=True,
                        help_text="Final validated data (after human corrections)",
                        null=True,
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who confirmed/rejected extraction",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_parsed_data",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "raw_file",
                    models.OneToOneField(
                        help_text="Original source file",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parsed_data",
                        to="core.rawfile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parsed_data_records",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parsed Data",
                "ordering": ["-extracted_at"],
            },
        ),
        migrations.CreateModel(
            name="ExecutionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(help_text="When protocol execution began"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When protocol execution finished",
                        null=True,
                    ),
                ),
                (
                    "validated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When technician confirmed results",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Currently Running"),
                            ("completed", "Completed"),
                            ("error", "Error/Failed"),
                            ("validated", "Validated by Technician"),
                        ],
                        db_index=True,
                        default="running",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Technician notes about execution"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft delete (data preserved for audit)",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Equipment used (Hamilton robot, spectrophotometer, etc.)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.equipment",
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        help_text="Which protocol was executed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="protocols.protocol",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        help_text="Technician who started execution",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="started_executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Technician who validated execution results",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_file",
                    models.ForeignKey(
                        blank=True,
                        help_text="Machine output file (CSV/JSON from equipment)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.rawfile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_logs",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddField(
            model_name="equipment",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipment",
                to="core.tenant",
            ),
        ),
        migrations.CreateModel(
            name="CertifiedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certified_at",
                    models.DateTimeField(
                        blank=True, help_text="When report was certified", null=True
                    ),
                ),
                (
                    "report_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 hash of PDF content (proof of originality)",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "chain_integrity_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Was audit chain verified before generation?",
                    ),
                ),
                (
                    "chain_verification_details",
                    models.JSONField(
                        default=dict,
                        help_text="Verification results: {total_records, verified, corrupted}",
                    ),
                ),
                (
                    "pdf_filename",
                    models.CharField(
                        help_text="Filename of certified PDF report", max_length=255
                    ),
                ),
                ("pdf_size", models.BigIntegerField(help_text="Size of PDF in bytes")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Certification"),
                            ("certified", "Certified & Auditable"),
                            ("revoked", "Revoked (chain corrupted)"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Certification state",
                        max_length=20,
                    ),
                ),
                (
                    "revocation_reason",
                    models.TextField(
                        blank=True, help_text="Reason for revocation if chain corrupted"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "certified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Technician/QA who certified this report",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certified_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "execution_log",
                    models.ForeignKey(
                        help_text="Protocol execution this report documents",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certified_reports",
                        to="core.executionlog",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Lab that generated this report",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certified_reports",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-certified_at"],
            },
        ),
        migrations.CreateModel(
            name="ExecutionStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "protocol_step_number",
                    models.IntegerField(
                        help_text="Step number in protocol (1, 2, 3, ...)"
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(
                        default=False,
                        help_text="Technician confirmed this step's result is correct",
                    ),
                ),
                (
                    "validation_notes",
                    models.TextField(
                        blank=True,
                        help_text="Technician notes (e.g., 'Value seems low, verified with backup')",
                    ),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="core.executionlog",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        help_text="Sample being processed in this step",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="samples.sample",
                    ),
                ),
                (
                    "parsed_data",
                    models.ForeignKey(
                        blank=True,
                        help_text="AI-extracted result from machine (e.g., measurement, image analysis)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="execution_steps",
                        to="core.parseddata",
                    ),
                ),
            ],
            options={
                "ordering": ["execution", "protocol_step_number"],
                "unique_together": {("execution", "protocol_step_number", "sample")},
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles_with_permission",
                        to="core.permission",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions_set",
                        to="core.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role Permission",
                "unique_together": {("role", "permission")},
            },
        ),
        migrations.AddIndex(
            model_name="rawfile",
            index=models.Index(
                fields=["tenant", "uploaded_at"], name="core_rawfil_tenant__bf0bf7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rawfile",
            index=models.Index(
                fields=["file_hash"], name="core_rawfil_file_ha_8809fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="parseddata",
            index=models.Index(
                fields=["tenant", "state"], name="core_parsed_tenant__1c87d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="parseddata",
            index=models.Index(
                fields=["raw_file"], name="core_parsed_raw_fil_e3d1c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="executionlog",
            index=models.Index(
                fields=["tenant", "status"], name="core_execut_tenant__56cf15_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="executionlog",
            index=models.Index(
                fields=["protocol", "started_at"], name="core_execut_protoco_bf5f68_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="certifiedreport",
            index=models.Index(
                fields=["tenant", "state"], name="core_certif_tenant__75c046_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="certifiedreport",
            index=models.Index(
                fields=["execution_log", "state"], name="core_certif_executi_76acbd_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="user",
            unique_together={("tenant", "username")},
        ),
    ]
