# Generated by Django 5.2.5 on 2026-02-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        help_text="Model name (e.g., 'Sample', 'Protocol')",
                        max_length=50,
                    ),
                ),
                (
                    "entity_id",
                    models.BigIntegerField(
                        help_text="Primary key of the affected entity"
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                        ],
                        help_text="CREATE, UPDATE, or DELETE",
                        max_length=10,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When the operation occurred (UTC, immutable)",
                    ),
                ),
                (
                    "user_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="ID of user who triggered the operation (future: auth system)",
                        null=True,
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email of user (for readability, actual proof is signature)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        default=dict,
                        help_text="{'field_name': {'before': old_value, 'after': new_value}, ...}",
                    ),
                ),
                (
                    "snapshot_before",
                    models.JSONField(
                        default=dict,
                        help_text="Full entity state BEFORE mutation (for forensics)",
                    ),
                ),
                (
                    "snapshot_after",
                    models.JSONField(
                        default=dict, help_text="Full entity state AFTER mutation"
                    ),
                ),
                (
                    "signature",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256(previous_signature + json(this_record))",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "previous_signature",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="SHA-256 of the previous audit log (chain proof)",
                        max_length=64,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log Entry",
                "verbose_name_plural": "Audit Log Entries",
                "db_table": "audit_log",
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id", "timestamp"],
                        name="audit_log_entity__cd587a_idx",
                    ),
                    models.Index(
                        fields=["signature"], name="audit_log_signatu_3264db_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="audit_log_timesta_e8e14e_idx"
                    ),
                ],
            },
        ),
    ]
