# Generated by Django 5.2.5 on 2026-02-25 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Connector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "connector_id",
                    models.SlugField(
                        help_text="Unique identifier (e.g., 'hamilton-microlab-star')",
                        unique=True,
                    ),
                ),
                (
                    "connector_name",
                    models.CharField(
                        help_text="Human-readable name (e.g., 'Hamilton Microlab STAR')",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="What this connector does and which machines it supports",
                    ),
                ),
                (
                    "connector_type",
                    models.CharField(
                        choices=[
                            (
                                "liquid_handler",
                                "Liquid Handler (Hamilton, Tecan, Eppendorf)",
                            ),
                            ("plate_reader", "Plate Reader (BioTek, Tecan, Infinite)"),
                            ("incubator", "Incubator"),
                            ("centrifuge", "Centrifuge"),
                            ("spectrophotometer", "Spectrophotometer"),
                            ("pcr_machine", "PCR/qPCR Machine"),
                            ("microscope", "Microscope"),
                            ("storage", "Sample Storage System"),
                            ("other", "Other Equipment"),
                        ],
                        help_text="SiLA 2 equipment category",
                        max_length=50,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0.0",
                        help_text="SiLA interface version (semantic versioning)",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active (Production Ready)"),
                            ("beta", "Beta (Testing)"),
                            ("deprecated", "Deprecated (Use newer version)"),
                        ],
                        default="active",
                        help_text="Is this connector ready for production?",
                        max_length=20,
                    ),
                ),
                (
                    "fdl_descriptor",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="SiLA 2 Feature Definition Language (FDL) - machine capabilities & output schema",
                    ),
                ),
                (
                    "pivot_model_mapping",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="How this connector's outputs map to Pivot Model fields",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Connector (SiLA 2 Driver)",
                "ordering": ["connector_type", "connector_name"],
            },
        ),
        migrations.CreateModel(
            name="ConnectorMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        help_text="Field name from machine output (e.g., 'dispense_volume')",
                        max_length=255,
                    ),
                ),
                (
                    "field_description",
                    models.TextField(
                        blank=True,
                        help_text="Human description of what this field represents",
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("string", "Text"),
                            ("float", "Decimal Number"),
                            ("integer", "Whole Number"),
                            ("boolean", "True/False"),
                            ("datetime", "Date/Time"),
                            ("json", "Structured Data"),
                        ],
                        help_text="Expected data type",
                        max_length=50,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="Unit of measurement (e.g., 'μL', '°C', 'seconds')",
                        max_length=100,
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False,
                        help_text="Must this field be present in machine output?",
                    ),
                ),
                (
                    "min_value",
                    models.FloatField(
                        blank=True,
                        help_text="Validation: minimum value (for numeric types)",
                        null=True,
                    ),
                ),
                (
                    "max_value",
                    models.FloatField(
                        blank=True,
                        help_text="Validation: maximum value (for numeric types)",
                        null=True,
                    ),
                ),
                (
                    "validation_regex",
                    models.CharField(
                        blank=True,
                        help_text="Regex pattern for validation (for string types)",
                        max_length=500,
                    ),
                ),
                (
                    "pivot_field",
                    models.CharField(
                        blank=True,
                        help_text="Our internal field name in Pivot Model (e.g., 'volume', 'temperature')",
                        max_length=255,
                    ),
                ),
                (
                    "confidence_default",
                    models.FloatField(
                        default=0.8,
                        help_text="Default AI confidence score for this mapping (0.0 to 1.0)",
                    ),
                ),
                (
                    "connector",
                    models.ForeignKey(
                        help_text="Which connector outputs this field",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="output_fields",
                        to="core.connector",
                    ),
                ),
            ],
            options={
                "verbose_name": "Connector Output Field (FDL)",
                "ordering": ["connector", "field_name"],
                "unique_together": {("connector", "field_name")},
            },
        ),
        migrations.CreateModel(
            name="TenantConnectorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "machine_instance_name",
                    models.CharField(
                        help_text="Name of this specific machine (e.g., 'Hamilton-Lab1')",
                        max_length=255,
                    ),
                ),
                (
                    "column_mapping",
                    models.JSONField(
                        default=dict,
                        help_text='{"Temp": "temperature", "Sample_ID": "sample_id", "Vol": "volume"}',
                    ),
                ),
                (
                    "mapping_confidence_scores",
                    models.JSONField(
                        default=dict,
                        help_text='{"Temp": 0.98, "Sample_ID": 0.95, "Vol": 0.87}',
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When user confirmed the mapping",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is this profile being used for new data?",
                    ),
                ),
                (
                    "mapping_model_version",
                    models.CharField(
                        blank=True,
                        help_text="Which AI model recognized this mapping (e.g., 'gpt-4-turbo')",
                        max_length=100,
                    ),
                ),
                (
                    "mapping_prompt_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 of prompt used for this mapping (reproducibility)",
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who confirmed this mapping",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_connector_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "connector",
                    models.ForeignKey(
                        help_text="Which connector this profile configures",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_profiles",
                        to="core.connector",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Which lab owns this profile",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connector_profiles",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Connector Profile (AI Mapping)",
                "ordering": ["-confirmed_at", "machine_instance_name"],
                "unique_together": {("tenant", "connector", "machine_instance_name")},
            },
        ),
    ]
