# Generated by Django 5.2.5 on 2026-03-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certifiedreport',
            name='pdf_filename',
            field=models.CharField(default='', help_text='Filename of certified PDF report', max_length=255),
        ),
        migrations.AlterField(
            model_name='certifiedreport',
            name='pdf_size',
            field=models.BigIntegerField(default=0, help_text='Size of PDF in bytes'),
        ),
        migrations.AlterField(
            model_name='certifiedreport',
            name='report_hash',
            field=models.CharField(db_index=True, default='', help_text='SHA-256 hash of PDF content (proof of originality)', max_length=64, unique=True),
        ),
    ]
