# Generated by Django 5.2.5 on 2026-02-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="timestamp",
            field=models.DateTimeField(
                db_index=True,
                help_text="When the operation occurred (UTC, immutable, set explicitly)",
            ),
        ),
    ]
