# Generated by Django 5.2.5 on 2026-03-12 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_certifiedreport_pdf_filename_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human-readable name (e.g., 'LabWare LIMS')", max_length=255)),
                ('url', models.URLField(help_text='HTTPS endpoint that receives POST notifications')),
                ('events', models.JSONField(default=list, help_text='List of event types to subscribe to (e.g., ["measurement.created", "sample.created"])')),
                ('secret', models.CharField(help_text='Shared secret for HMAC-SHA256 signature verification', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('last_status_code', models.IntegerField(blank=True, null=True)),
                ('failure_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, default='')),
                ('success', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, default='')),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='core.webhooksubscription')),
            ],
            options={
                'ordering': ['-delivered_at'],
            },
        ),
    ]
