# Generated by Django 5.2.5 on 2026-03-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_webhook_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='certifiedreport',
            name='signature_meaning',
            field=models.CharField(blank=True, choices=[('review', 'Review'), ('approval', 'Approval'), ('responsibility', 'Responsibility'), ('authorship', 'Authorship'), ('verification', 'Verification')], default='', help_text='Meaning of the electronic signature (21 CFR Part 11 §11.50)', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_enabled',
            field=models.BooleanField(default=False, help_text='Whether TOTP 2FA is active for this user'),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, default='', help_text='Base32-encoded TOTP secret key', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_verified_at',
            field=models.DateTimeField(blank=True, help_text='When TOTP was first verified and activated', null=True),
        ),
    ]
