# Generated by Django 5.2.5 on 2026-02-17 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_permission_role_tenant_rolepermission_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        help_text="Original filename from upload", max_length=255
                    ),
                ),
                (
                    "file_content",
                    models.BinaryField(
                        help_text="Complete file content (never modified)"
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 hash of file content (proof of originality)",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("file_size", models.BigIntegerField(help_text="File size in bytes")),
                (
                    "mime_type",
                    models.CharField(
                        help_text="MIME type (e.g., 'text/csv', 'application/pdf')",
                        max_length=100,
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When file was uploaded"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft delete flag (content preserved for audit)",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant (lab) that uploaded the file",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_files",
                        to="core.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who uploaded the file",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Raw File",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ParsedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "extracted_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When AI extraction occurred"
                    ),
                ),
                (
                    "parsed_json",
                    models.JSONField(
                        help_text="Raw AI-extracted data (not yet validated)"
                    ),
                ),
                (
                    "extraction_confidence",
                    models.FloatField(help_text="AI confidence score (0.0 to 1.0)"),
                ),
                (
                    "extraction_model",
                    models.CharField(
                        help_text="Which AI model was used (e.g., 'gpt-4-turbo')",
                        max_length=100,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Awaiting Validation"),
                            ("validated", "Human Confirmed"),
                            ("rejected", "Human Rejected"),
                            ("superseded", "Replaced by New Parse"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current validation state",
                        max_length=20,
                    ),
                ),
                (
                    "validated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When human validation occurred",
                        null=True,
                    ),
                ),
                (
                    "validation_notes",
                    models.TextField(
                        blank=True,
                        help_text="Human notes on validation (e.g., corrections made)",
                    ),
                ),
                (
                    "confirmed_json",
                    models.JSONField(
                        blank=True,
                        help_text="Final validated data (after human corrections)",
                        null=True,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parsed_data_records",
                        to="core.tenant",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who confirmed/rejected extraction",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_parsed_data",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "raw_file",
                    models.OneToOneField(
                        help_text="Original source file",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parsed_data",
                        to="core.rawfile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parsed Data",
                "ordering": ["-extracted_at"],
            },
        ),
        migrations.AddIndex(
            model_name="rawfile",
            index=models.Index(
                fields=["tenant", "uploaded_at"], name="core_rawfil_tenant__bf0bf7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rawfile",
            index=models.Index(
                fields=["file_hash"], name="core_rawfil_file_ha_8809fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="parseddata",
            index=models.Index(
                fields=["tenant", "state"], name="core_parsed_tenant__1c87d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="parseddata",
            index=models.Index(
                fields=["raw_file"], name="core_parsed_raw_fil_e3d1c7_idx"
            ),
        ),
    ]
