# Generated by Django 5.2.5 on 2026-02-17 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rawfile_parseddata_and_more"),
        ("protocols", "0002_protocol_deleted_at_protocol_is_deleted_and_more"),
        ("samples", "0003_sample_deleted_at_sample_is_deleted_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "equipment_id",
                    models.CharField(
                        help_text="Unique equipment identifier (from parsed file)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "equipment_name",
                    models.CharField(help_text="Human-readable name", max_length=255),
                ),
                (
                    "equipment_type",
                    models.CharField(
                        choices=[
                            ("liquid_handler", "Liquid Handler (Hamilton, Tecan)"),
                            ("spectrophotometer", "Spectrophotometer"),
                            ("plate_reader", "Plate Reader (Fluor, Absorbance)"),
                            ("incubator", "Incubator"),
                            ("centrifuge", "Centrifuge"),
                            ("pcr_machine", "PCR/qPCR Machine"),
                            ("microscope", "Microscope"),
                            ("freezer", "Freezer Storage"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Physical location in lab", max_length=255
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        help_text="Serial number for traceability",
                        max_length=100,
                    ),
                ),
                (
                    "last_calibration",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last calibration date (critical for accuracy)",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("operational", "Operational"),
                            ("maintenance", "In Maintenance"),
                            ("broken", "Broken"),
                            ("decommissioned", "Decommissioned"),
                        ],
                        default="operational",
                        max_length=20,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["equipment_name"],
            },
        ),
        migrations.CreateModel(
            name="ExecutionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(help_text="When protocol execution began"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When protocol execution finished",
                        null=True,
                    ),
                ),
                (
                    "validated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When technician confirmed results",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Currently Running"),
                            ("completed", "Completed"),
                            ("error", "Error/Failed"),
                            ("validated", "Validated by Technician"),
                        ],
                        db_index=True,
                        default="running",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Technician notes about execution"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft delete (data preserved for audit)",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Equipment used (Hamilton robot, spectrophotometer, etc.)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.equipment",
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        help_text="Which protocol was executed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="protocols.protocol",
                    ),
                ),
                (
                    "source_file",
                    models.ForeignKey(
                        blank=True,
                        help_text="Machine output file (CSV/JSON from equipment)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.rawfile",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        help_text="Technician who started execution",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="started_executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_logs",
                        to="core.tenant",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Technician who validated execution results",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ExecutionStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "protocol_step_number",
                    models.IntegerField(
                        help_text="Step number in protocol (1, 2, 3, ...)"
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(
                        default=False,
                        help_text="Technician confirmed this step's result is correct",
                    ),
                ),
                (
                    "validation_notes",
                    models.TextField(
                        blank=True,
                        help_text="Technician notes (e.g., 'Value seems low, verified with backup')",
                    ),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="core.executionlog",
                    ),
                ),
                (
                    "parsed_data",
                    models.ForeignKey(
                        blank=True,
                        help_text="AI-extracted result from machine (e.g., measurement, image analysis)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="execution_steps",
                        to="core.parseddata",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        help_text="Sample being processed in this step",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="samples.sample",
                    ),
                ),
            ],
            options={
                "ordering": ["execution", "protocol_step_number"],
            },
        ),
        migrations.AddIndex(
            model_name="executionlog",
            index=models.Index(
                fields=["tenant", "status"], name="core_execut_tenant__56cf15_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="executionlog",
            index=models.Index(
                fields=["protocol", "started_at"], name="core_execut_protoco_bf5f68_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="executionstep",
            unique_together={("execution", "protocol_step_number", "sample")},
        ),
    ]
