# Generated by Django 5.2.5 on 2026-02-17 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_equipment_executionlog_executionstep_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertifiedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certified_at",
                    models.DateTimeField(
                        blank=True, help_text="When report was certified", null=True
                    ),
                ),
                (
                    "report_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 hash of PDF content (proof of originality)",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "chain_integrity_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Was audit chain verified before generation?",
                    ),
                ),
                (
                    "chain_verification_details",
                    models.JSONField(
                        default=dict,
                        help_text="Verification results: {total_records, verified, corrupted}",
                    ),
                ),
                (
                    "pdf_filename",
                    models.CharField(
                        help_text="Filename of certified PDF report", max_length=255
                    ),
                ),
                ("pdf_size", models.BigIntegerField(help_text="Size of PDF in bytes")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Certification"),
                            ("certified", "Certified & Auditable"),
                            ("revoked", "Revoked (chain corrupted)"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Certification state",
                        max_length=20,
                    ),
                ),
                (
                    "revocation_reason",
                    models.TextField(
                        blank=True, help_text="Reason for revocation if chain corrupted"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "certified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Technician/QA who certified this report",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certified_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "execution_log",
                    models.ForeignKey(
                        help_text="Protocol execution this report documents",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certified_reports",
                        to="core.executionlog",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Lab that generated this report",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certified_reports",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-certified_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "state"],
                        name="core_certif_tenant__75c046_idx",
                    ),
                    models.Index(
                        fields=["execution_log", "state"],
                        name="core_certif_executi_76acbd_idx",
                    ),
                ],
            },
        ),
    ]
