# Generated by Django 5.2.5 on 2026-03-05 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(help_text='Business identifier (e.g., SMP-2024-001)', max_length=100, unique=True)),
                ('batch_number', models.CharField(help_text='Batch or lot number', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_by', models.CharField(help_text='Username or identifier of the creator', max_length=255)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.ForeignKey(help_text='Instrument that processes this sample', on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='instruments.instrument')),
            ],
            options={
                'indexes': [models.Index(fields=['is_deleted', 'id'], name='samples_sam_is_dele_66b428_idx'), models.Index(fields=['status'], name='samples_sam_status_431764_idx'), models.Index(fields=['batch_number'], name='samples_sam_batch_n_f2c852_idx')],
            },
        ),
    ]
