# Generated by Django 5.2.5 on 2026-02-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0002_rename_type_to_sample_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when logically deleted (null if not deleted)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Logical deletion marker (data is never physically removed)",
            ),
        ),
        migrations.AddIndex(
            model_name="sample",
            index=models.Index(
                fields=["is_deleted", "id"], name="samples_sam_is_dele_66b428_idx"
            ),
        ),
    ]
