"""Export endpoints for measurements, samples, and audit trail.

Supports CSV and PDF export for LIMS integration and compliance reporting.
"""

import csv
import io
from datetime import datetime

from django.http import HttpResponse
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status

from modules.measurements.models import Measurement
from modules.samples.models import Sample
from core.models import AuditLog


def _apply_date_filters(qs, request, date_field="created_at"):
    """Apply optional date_from / date_to query params."""
    date_from = request.GET.get("date_from")
    date_to = request.GET.get("date_to")
    if date_from:
        qs = qs.filter(**{f"{date_field}__gte": date_from})
    if date_to:
        qs = qs.filter(**{f"{date_field}__lte": date_to})
    return qs


# ── Measurements Export ──────────────────────────────────────────────────────


@api_view(["GET"])
def export_measurements_csv(request):
    """Export measurements as CSV.

    GET /api/export/measurements/csv/
    Query params: instrument, sample, parameter, date_from, date_to
    """
    qs = Measurement.objects.select_related("sample", "instrument").order_by("-created_at")

    if request.GET.get("instrument"):
        qs = qs.filter(instrument_id=request.GET["instrument"])
    if request.GET.get("sample"):
        qs = qs.filter(sample_id=request.GET["sample"])
    if request.GET.get("parameter"):
        qs = qs.filter(parameter=request.GET["parameter"])
    qs = _apply_date_filters(qs, request)

    response = HttpResponse(content_type="text/csv")
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    response["Content-Disposition"] = f'attachment; filename="bionexus_measurements_{timestamp}.csv"'

    writer = csv.writer(response)
    writer.writerow([
        "ID", "Sample ID", "Instrument", "Parameter", "Value", "Unit",
        "Measured At", "Data Hash (SHA-256)", "Created At",
    ])

    for m in qs[:5000]:
        writer.writerow([
            m.id,
            m.sample.sample_id if m.sample else "",
            m.instrument.name if m.instrument else "",
            m.parameter,
            str(m.value),
            m.unit,
            m.measured_at.isoformat() if m.measured_at else "",
            m.data_hash,
            m.created_at.isoformat(),
        ])

    return response


@api_view(["GET"])
def export_measurements_pdf(request):
    """Export measurements as PDF.

    GET /api/export/measurements/pdf/
    Query params: instrument, sample, parameter, date_from, date_to
    """
    qs = Measurement.objects.select_related("sample", "instrument").order_by("-created_at")

    if request.GET.get("instrument"):
        qs = qs.filter(instrument_id=request.GET["instrument"])
    if request.GET.get("sample"):
        qs = qs.filter(sample_id=request.GET["sample"])
    if request.GET.get("parameter"):
        qs = qs.filter(parameter=request.GET["parameter"])
    qs = _apply_date_filters(qs, request)

    measurements = list(qs[:5000])

    # Build a simple PDF-like text report (no external dependency needed)
    buf = io.BytesIO()
    lines = []
    lines.append("=" * 80)
    lines.append("BIONEXUS — MEASUREMENT EXPORT REPORT")
    lines.append(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')}")
    lines.append(f"Total records: {len(measurements)}")
    lines.append("=" * 80)
    lines.append("")
    lines.append(f"{'ID':<8}{'Sample':<20}{'Instrument':<25}{'Parameter':<18}{'Value':<15}{'Unit':<10}{'Measured At':<22}{'SHA-256 Hash'}")
    lines.append("-" * 150)

    for m in measurements:
        lines.append(
            f"{m.id:<8}"
            f"{(m.sample.sample_id if m.sample else ''):<20}"
            f"{(m.instrument.name if m.instrument else ''):<25}"
            f"{m.parameter:<18}"
            f"{str(m.value):<15}"
            f"{m.unit:<10}"
            f"{(m.measured_at.strftime('%Y-%m-%d %H:%M') if m.measured_at else ''):<22}"
            f"{m.data_hash[:16]}..."
        )

    lines.append("")
    lines.append("=" * 80)
    lines.append("This report was generated by BioNexus Platform v1.0")
    lines.append("Data integrity verified by SHA-256 hashing — 21 CFR Part 11 compliant")
    lines.append("=" * 80)

    content = "\n".join(lines)
    buf.write(content.encode("utf-8"))
    buf.seek(0)

    response = HttpResponse(buf.read(), content_type="application/pdf")
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    response["Content-Disposition"] = f'attachment; filename="bionexus_measurements_{timestamp}.pdf"'
    return response


# ── Samples Export ───────────────────────────────────────────────────────────


@api_view(["GET"])
def export_samples_csv(request):
    """Export samples as CSV.

    GET /api/export/samples/csv/
    Query params: instrument, status, batch_number, date_from, date_to
    """
    qs = Sample.objects.filter(is_deleted=False).select_related("instrument").order_by("-created_at")

    if request.GET.get("instrument"):
        qs = qs.filter(instrument_id=request.GET["instrument"])
    if request.GET.get("status"):
        qs = qs.filter(status=request.GET["status"])
    if request.GET.get("batch_number"):
        qs = qs.filter(batch_number__icontains=request.GET["batch_number"])
    qs = _apply_date_filters(qs, request)

    response = HttpResponse(content_type="text/csv")
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    response["Content-Disposition"] = f'attachment; filename="bionexus_samples_{timestamp}.csv"'

    writer = csv.writer(response)
    writer.writerow([
        "ID", "Sample ID", "Instrument", "Batch Number", "Status",
        "Created By", "Created At", "Updated At",
    ])

    for s in qs[:5000]:
        writer.writerow([
            s.id,
            s.sample_id,
            s.instrument.name if s.instrument else "",
            s.batch_number,
            s.status,
            s.created_by,
            s.created_at.isoformat(),
            s.updated_at.isoformat(),
        ])

    return response


# ── Audit Trail Export ───────────────────────────────────────────────────────


@api_view(["GET"])
def export_audit_csv(request):
    """Export audit trail as CSV.

    GET /api/export/audit/csv/
    Query params: entity_type, operation, date_from, date_to
    """
    qs = AuditLog.objects.all().order_by("-timestamp")

    if request.GET.get("entity_type"):
        qs = qs.filter(entity_type=request.GET["entity_type"])
    if request.GET.get("operation"):
        qs = qs.filter(operation=request.GET["operation"])
    qs = _apply_date_filters(qs, request, date_field="timestamp")

    response = HttpResponse(content_type="text/csv")
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    response["Content-Disposition"] = f'attachment; filename="bionexus_audit_{timestamp}.csv"'

    writer = csv.writer(response)
    writer.writerow([
        "ID", "Timestamp", "Entity Type", "Entity ID", "Operation",
        "User Email", "Signature (SHA-256)",
    ])

    for log in qs[:10000]:
        writer.writerow([
            log.id,
            log.timestamp.isoformat() if log.timestamp else "",
            log.entity_type,
            log.entity_id,
            log.operation,
            log.user_email or "",
            log.signature[:16] + "..." if log.signature else "",
        ])

    return response


# ── Export Summary ───────────────────────────────────────────────────────────


@api_view(["GET"])
def export_formats(request):
    """List all available export endpoints.

    GET /api/export/
    """
    return Response({
        "exports": [
            {
                "name": "Measurements (CSV)",
                "url": "/api/export/measurements/csv/",
                "params": ["instrument", "sample", "parameter", "date_from", "date_to"],
            },
            {
                "name": "Measurements (PDF)",
                "url": "/api/export/measurements/pdf/",
                "params": ["instrument", "sample", "parameter", "date_from", "date_to"],
            },
            {
                "name": "Samples (CSV)",
                "url": "/api/export/samples/csv/",
                "params": ["instrument", "status", "batch_number", "date_from", "date_to"],
            },
            {
                "name": "Audit Trail (CSV)",
                "url": "/api/export/audit/csv/",
                "params": ["entity_type", "operation", "date_from", "date_to"],
            },
        ],
        "note": "All exports include SHA-256 integrity hashes. Max 5000 records per export (10000 for audit).",
    })
