# Generated by Django 5.2.5 on 2026-03-12 07:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PendingMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Hub-generated UUID to prevent duplicate ingestion on retry', unique=True)),
                ('sample_id', models.IntegerField(help_text='Raw FK to samples.Sample (no constraint for offline)')),
                ('instrument_id', models.IntegerField(help_text='Raw FK to instruments.Instrument (no constraint for offline)')),
                ('parameter', models.CharField(help_text='What was measured (e.g., pH, temperature, absorbance)', max_length=255)),
                ('value', models.DecimalField(decimal_places=10, help_text='Measured value', max_digits=20)),
                ('unit', models.CharField(help_text='Unit of measurement', max_length=50)),
                ('data_hash', models.CharField(help_text='SHA-256 from instrument. SACRED: never recomputed server-side', max_length=64)),
                ('source_timestamp', models.DateTimeField(help_text='Instrument emission timestamp. SACRED: never overwritten')),
                ('hub_received_at', models.DateTimeField(help_text='Hub local RTC time when data arrived at the WAL')),
                ('server_received_at', models.DateTimeField(blank=True, help_text='Server UTC time when data was ingested (set at ingest)', null=True)),
                ('clock_drift_ms', models.IntegerField(blank=True, help_text='Delta (server_received_at - hub_received_at) in milliseconds', null=True)),
                ('drift_flagged', models.BooleanField(default=False, help_text='True if |clock_drift_ms| exceeds configured threshold')),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('syncing', 'Syncing'), ('synced', 'Synced'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('retry_count', models.IntegerField(default=0, help_text='Number of failed sync attempts')),
                ('last_error', models.TextField(blank=True, help_text='Last sync error message')),
                ('synced_measurement_id', models.IntegerField(blank=True, help_text='Server-side Measurement PK after successful ACK', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['sync_status', 'created_at'], name='persistence_sync_st_f5ae40_idx'), models.Index(fields=['drift_flagged'], name='persistence_drift_f_a33249_idx')],
            },
        ),
    ]
