# Generated by Django 5.2.5 on 2026-03-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Instrument display name', max_length=255)),
                ('instrument_type', models.CharField(help_text='e.g., spectrophotometer, pH meter, HPLC', max_length=100)),
                ('serial_number', models.CharField(help_text='Manufacturer serial number', max_length=255, unique=True)),
                ('connection_type', models.CharField(choices=[('RS232', 'RS232'), ('USB', 'USB'), ('Ethernet', 'Ethernet'), ('WiFi', 'WiFi')], help_text='Physical connection method', max_length=20)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('error', 'Error')], default='offline', max_length=20)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['is_deleted', 'id'], name='instruments_is_dele_a033ae_idx'), models.Index(fields=['status'], name='instruments_status_4c19cf_idx')],
            },
        ),
    ]
