# Generated by Django 5.2.5 on 2026-04-22 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parser_type', models.CharField(choices=[('mettler_sics_v1', 'Mettler Toledo SICS'), ('sartorius_sbi_v1', 'Sartorius SBI'), ('generic_csv_v1', 'Generic CSV'), ('agilent_chemstation_v1', 'Agilent ChemStation'), ('waters_empower_v1', 'Waters Empower'), ('dissolution_ascii_v1', 'Dissolution ASCII')], help_text='Parser protocol from the registry (GAMP5 Cat 4 binding)', max_length=50)),
                ('units', models.CharField(blank=True, default='', help_text='Default measurement unit for this instrument (e.g., g, pH, AU, mg/L)', max_length=50)),
                ('required_metadata_fields', models.JSONField(blank=True, default=list, help_text='List of MeasurementContext fields that must be provided. e.g., ["operator", "lot_number", "method"]')),
                ('thresholds', models.JSONField(blank=True, default=dict, help_text='Threshold rules per parameter. Keys: parameter names, values: {warn, block, min, max, unit, action}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, help_text='Who created this config (pseudonymized operator ID)', max_length=255)),
                ('instrument', models.OneToOneField(help_text='The instrument this configuration applies to', on_delete=django.db.models.deletion.CASCADE, related_name='config', to='instruments.instrument')),
            ],
            options={
                'verbose_name': 'Instrument Configuration',
                'verbose_name_plural': 'Instrument Configurations',
            },
        ),
    ]
