# Generated by Django 5.2.5 on 2026-05-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_add_context_and_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentconfig',
            name='parser_type',
            field=models.CharField(choices=[('mettler_sics_v1', 'Mettler Toledo SICS'), ('sartorius_sbi_v1', 'Sartorius SBI'), ('generic_csv_v1', 'Generic CSV'), ('agilent_chemstation_v1', 'Agilent ChemStation'), ('karl_fischer_v1', 'Karl Fischer Titrator'), ('waters_empower_v1', 'Waters Empower'), ('dissolution_ascii_v1', 'Dissolution ASCII')], help_text='Parser protocol from the registry (GAMP5 Cat 4 binding)', max_length=50),
        ),
    ]
