version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-bionexus}
      POSTGRES_USER: ${POSTGRES_USER:-bionexus}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-bionexus}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: python:3.11
    working_dir: /app
    volumes:
      - ./backend:/app
    command: >-
      sh -c "pip install -r requirements.txt && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      DJANGO_SETTINGS_MODULE: core.settings
      DATABASE_URL: "${DATABASE_URL:-postgres://bionexus:bionexus@db:5432/bionexus}"
      POSTGRES_DB: ${POSTGRES_DB:-bionexus}
      POSTGRES_USER: ${POSTGRES_USER:-bionexus}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-bionexus}
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:

