name: CI

on:
  pull_request:
  push:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install pinned dependencies
        run: |
          pip install --upgrade pip
          pip install -r bionexus-platform/backend/requirements.txt

      - name: Run tests
        working-directory: bionexus-platform/backend
        run: |
          pytest -q

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Cache frontend node modules
        id: frontend-cache
        uses: actions/cache@v3
        with:
          path: bionexus-platform/frontend/node_modules
          key: ${{ runner.os }}-frontend-${{ hashFiles('bionexus-platform/frontend/package-lock.json') }}
          restore-keys: ${{ runner.os }}-frontend-

      - name: Install frontend dependencies
        if: steps.frontend-cache.outputs.cache-hit != 'true'
        working-directory: bionexus-platform/frontend
        run: npm ci

      - name: Run frontend tests
        working-directory: bionexus-platform/frontend
        run: npm test
